baseURL = 'https://fracz.github.io/dydaktyka/issi/movies-fullstack'
languageCode = 'pl-pl'
title = 'Movies Fullstack'
theme = 'relearn'
themesDir = '../../themes'
publishDir = '../../public/issi/movies-fullstack'

defaultContentLanguage = "pl"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
canonifyurls = true

[params]
editURL = "https://github.com/fracz/dydaktyka/edit/main/issi/movies-fullstack/content/"
author.name = "Wojciech FrÄ…cz"
showVisitedLinks = false
disableSearch = true
disableBreadcrumb = true
disableAssetsBusting = false
disableInlineCopyToClipBoard = false
disableShortcutsTitle = false
disableLanguageSwitchingButton = true
ordersectionsby = "weight"
themeVariant = "green" # choose theme variant "green", "gold" , "gray", "blue" (default)

  [params.imageEffects]
    border = true
    lazy = true
    lightbox = false
    shadow = false

[outputs]
home = [ "HTML" ]

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
